### ISSUE TITLE
Bug in calc_qflux.ncl

### ISSUE THREAD

**Issue by apendergrass** [NCAR/simpler_models#3]
There are a few places in the script where Fnet is found (first instance: Line 12), though that isn't defined. Seems that it should be qflux, or in later cases Qflux - though I'm not 100% sure. Thanks for posting the script!!

**Comment by brianpm** [comment]
I replaced the Fnet with qflux in the function calc_qflux. Other instances of Fnet appear to be in comments. I think this should fix the issue, so I will close.
